sonar.projectKey=python-sample-project
sonar.projectName=Python Project1

# Source code location
sonar.sources=.

# Python-specific settings
sonar.python.version=3

# Optional but useful
sonar.exclusions=**/node_modules/**,**/__pycache__/**

# Encoding
sonar.sourceEncoding=UTF-8