# Unique identifier for your project in SonarQube
sonar.projectKey=nodejs-sample-project
sonar.projectName=NodeJS Sample Project
sonar.projectVersion=1.0

# Path to the source code
sonar.sources=.

# Exclusions (we don't want to scan dependencies)
sonar.exclusions=node_modules/**, test/**

# Encoding of the source code
sonar.sourceEncoding=UTF-8
